### ISSUE TITLE
License changing

### ISSUE THREAD

**Issue by drnextgis** [imincik/pghistory-tracker#7]
This is question to all contributors:
* @imincik
* @drnextgis 
* @sdikiy 

Would you consider changing the license to something like GPL v2 or later (note 'or later')?
This changing will make pghistory-tracker compatible with GPLv3 (see [compatibility matrix](http://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility)).

+1 from me

**Comment by imincik** [comment]
+ 1 from myself

**Comment by drnextgis** [comment]
It looks like all contributors are agreed. @imincik could you update license?

**Comment by imincik** [comment]
@drnextgis, can I ask you to prepare pull request for that ? Thank you.

**Comment by drnextgis** [comment]
PR https://github.com/imincik/pghistory-tracker/pull/8

**Comment by drnextgis** [comment]
Closed via https://github.com/imincik/pghistory-tracker/commit/8d14bc077c987e1f5a5fdb54d20048a492111489
